python manage.py loaddata app\fixtures\10_company.json
python manage.py loaddata app\fixtures\11_address.json
python manage.py loaddata app\fixtures\12_phone.json
python manage.py loaddata app\fixtures\13_benefit_type.json
python manage.py loaddata app\fixtures\14_document_type.json
python manage.py loaddata app\fixtures\15_benefit_policy_key.json
python manage.py loaddata app\fixtures\16_benefit_policy_type.json
python manage.py loaddata app\fixtures\17_supplemental_life_insurance_condition.json
python manage.py loaddata app\fixtures\21_benefit_plan.json
python manage.py loaddata app\fixtures\22_benefit_details.json
python manage.py loaddata app\fixtures\23_auth_user.json
python manage.py loaddata app\fixtures\24_person.json
python manage.py loaddata app\fixtures\25_signature.json
python manage.py loaddata app\fixtures\26_supplemental_life_insurance.json
python manage.py loaddata app\fixtures\27_compensation_update_reason.json
python manage.py loaddata app\fixtures\31_company_benefit_plan_option.json
python manage.py loaddata app\fixtures\32_enrolled.json
python manage.py loaddata app\fixtures\33_emergency_contact.json
python manage.py loaddata app\fixtures\34_company_user.json
python manage.py loaddata app\fixtures\34_document.json
python manage.py loaddata app\fixtures\35_w4.json
python manage.py loaddata app\fixtures\36_employment_authorization.json
python manage.py loaddata app\fixtures\37_fsa_plan.json
python manage.py loaddata app\fixtures\38_supplemental_life_rate.json
python manage.py loaddata app\fixtures\39_company_supplement_life_insurance.json
python manage.py loaddata app\fixtures\41_user_company_benefit_plan_option.json
python manage.py loaddata app\fixtures\42_company_fsa.json
python manage.py loaddata app\fixtures\43_fsa.json
python manage.py loaddata app\fixtures\44_person_company_suppl_life.json
python manage.py loaddata app\fixtures\45_suppl_life_beneficiary.json
python manage.py loaddata app\fixtures\46_hra_plan.json
python manage.py loaddata app\fixtures\47_company_hra_plan.json
python manage.py loaddata app\fixtures\48_person_company_hra_plan.json
python manage.py loaddata app\fixtures\49_period_definition.json
python manage.py loaddata app\fixtures\50_employee_compensation.json
python manage.py loaddata app\fixtures\51_employee_timetracking.json
python manage.py loaddata app\fixtures\52_company_1095_c.json
python manage.py loaddata app\fixtures\53_company_commuter_plan.json
python manage.py loaddata app\fixtures\54_person_company_commuter_plan.json
python manage.py loaddata app\fixtures\55_employee_1095_c.json
python manage.py loaddata app\fixtures\56_company_extra_benefit_plan.json
python manage.py loaddata app\fixtures\57_extra_benefit_item.json
python manage.py loaddata app\fixtures\58_person_company_extra_benefit_plan.json
python manage.py loaddata app\fixtures\59_person_company_extra_benefit_plan_item.json
python manage.py loaddata app\fixtures\60_company_1094_c.json
python manage.py loaddata app\fixtures\61_company_group.json
python manage.py loaddata app\fixtures\62_company_group_member.json
python manage.py loaddata app\fixtures\63_company_group_basic_life_insurance_plan.json
python manage.py loaddata app\fixtures\64_company_group_supplemental_life_insurance_plan.json
python manage.py loaddata app\fixtures\65_hsa_plan.json
python manage.py loaddata app\fixtures\66_company_group_benefit_plan_option.json
python manage.py loaddata app\fixtures\67_company_group_std_insurance_plan.json
python manage.py loaddata app\fixtures\68_company_group_hra_plan.json
python manage.py loaddata app\fixtures\69_company_group_ltd_insurance_plan.json
python manage.py loaddata app\fixtures\70_company_group_fsa_plan.json
python manage.py loaddata app\fixtures\71_company_group_commuter_plan.json
python manage.py loaddata app\fixtures\72_user_onboarding_step_state.json
python manage.py loaddata app\fixtures\73_company_service_providers.json
python manage.py loaddata app\fixtures\73_email_block_list.json
python manage.py loaddata app\fixtures\company_features.json
python manage.py loaddata app\fixtures\direct_deposit.json
python manage.py loaddata app\fixtures\employee_profile.json
python manage.py loaddata app\fixtures\life_insurance.json
python manage.py loaddata app\fixtures\ltd_insurance.json
python manage.py loaddata app\fixtures\std_insurance.json
python manage.py loaddata app\fixtures\sys_application_feature.json
python manage.py loaddata app\fixtures\sys_benefit_update_reason.json
python manage.py loaddata app\fixtures\sys_benefit_update_reason_category.json
python manage.py loaddata app\fixtures\upload.json
python manage.py loaddata app\fixtures\upload_application_feature.json
python manage.py loaddata app\fixtures\upload_for_user.json
python manage.py loaddata app\fixtures\user_bank_account.json
python manage.py loaddata app\fixtures\waived_benefit.json
