python manage.py loaddata app\fixtures\10_company.json
python manage.py loaddata app\fixtures\11_address.json
python manage.py loaddata app\fixtures\12_phone.json
python manage.py loaddata app\fixtures\13_benefit_type.json
python manage.py loaddata app\fixtures\14_document_type.json
python manage.py loaddata app\fixtures\15_benefit_policy_key.json
python manage.py loaddata app\fixtures\16_benefit_policy_type.json
python manage.py loaddata app\fixtures\17_supplemental_life_insurance_condition.json
python manage.py loaddata app\fixtures\21_benefit_plan.json
python manage.py loaddata app\fixtures\22_benefit_details.json
python manage.py loaddata app\fixtures\23_auth_user.json
python manage.py loaddata app\fixtures\24_person.json
python manage.py loaddata app\fixtures\25_signature.json
python manage.py loaddata app\fixtures\26_supplemental_life_insurance.json
python manage.py loaddata app\fixtures\27_compensation_update_reason.json
python manage.py loaddata app\fixtures\31_company_benefit_plan_option.json
python manage.py loaddata app\fixtures\32_enrolled.json
python manage.py loaddata app\fixtures\33_emergency_contact.json
python manage.py loaddata app\fixtures\34_company_user.json
python manage.py loaddata app\fixtures\34_document.json
python manage.py loaddata app\fixtures\35_w4.json
python manage.py loaddata app\fixtures\36_employment_authorization.json
python manage.py loaddata app\fixtures\37_fsa_plan.json
python manage.py loaddata app\fixtures\38_supplemental_life_rate.json
python manage.py loaddata app\fixtures\39_company_supplement_life_insurance.json
python manage.py loaddata app\fixtures\41_user_company_benefit_plan_option.json
python manage.py loaddata app\fixtures\42_company_fsa.json
python manage.py loaddata app\fixtures\43_fsa.json
python manage.py loaddata app\fixtures\44_person_company_suppl_life.json
python manage.py loaddata app\fixtures\45_suppl_life_beneficiary.json
python manage.py loaddata app\fixtures\46_hra_plan.json
python manage.py loaddata app\fixtures\47_company_hra_plan.json
python manage.py loaddata app\fixtures\48_person_company_hra_plan.json
python manage.py loaddata app\fixtures\49_period_definition.json
python manage.py loaddata app\fixtures\50_employee_compensation.json
python manage.py loaddata app\fixtures\51_employee_timetracking.json
python manage.py loaddata app\fixtures\52_company_1095_c.json
python manage.py loaddata app\fixtures\53_company_commuter_plan.json
python manage.py loaddata app\fixtures\54_person_company_commuter_plan.json
python manage.py loaddata app\fixtures\company_features.json
python manage.py loaddata app\fixtures\direct_deposit.json
python manage.py loaddata app\fixtures\employee_profile.json
python manage.py loaddata app\fixtures\life_insurance.json
python manage.py loaddata app\fixtures\ltd_insurance.json
python manage.py loaddata app\fixtures\std_insurance.json
python manage.py loaddata app\fixtures\sys_application_feature.json
python manage.py loaddata app\fixtures\sys_benefit_update_reason.json
python manage.py loaddata app\fixtures\sys_benefit_update_reason_category.json
python manage.py loaddata app\fixtures\upload.json
python manage.py loaddata app\fixtures\upload_application_feature.json
python manage.py loaddata app\fixtures\upload_audience.json
python manage.py loaddata app\fixtures\user_bank_account.json
python manage.py loaddata app\fixtures\waived_benefit.json
