update app_documenttype
set default_content = '
             {{CompanyName}}
CONFIDENTIAL INFORMATION AND INVENTION ASSIGNMENT AGREEMENT
Employee Name:{{EmployeeName}}
Effective Date:{{TodayDate}}
      As a condition of my becoming employed (or my employment being continued) by {{CompanyName}}, a Massachusetts corporation, or any of its current or future subsidiaries, affiliates, successors or assigns (collectively, the ?Company?), and in consideration of my employment with the Company and my receipt of the compensation now and hereafter paid to me by the Company, I agree to the following:
      1.    Relationship.  This Confidential Information and Invention Assignment Agreement (this ?Agreement?) will apply to my employment relationship with the Company.  If that relationship ends and the Company, within a year thereafter, either reemploys me or engages me as a consultant, I agree that this Agreement will also apply to such later employment or consulting relationship, unless the Company and I otherwise agree in writing.  Any such employment or consulting relationship between the parties hereto, whether commenced prior to, upon or after the date of this Agreement, is referred to herein as the ?Relationship.?
      2.    Duties.  I will perform for the Company such duties as may be designated by the Company from time to time or that are otherwise within the scope of the Relationship and not contrary to instructions from the Company.  During the Relationship, I will devote my entire best business efforts to the interests of the Company and will not engage in other employment or in any activities detrimental to the best interests of the Company without the prior written consent of the Company.
      3.    Confidential Information.
            (a) Protection of Information.  I understand that during the Relationship, the Company intends to provide me with information, including Confidential Information (as defined below), without which I would not be able to perform my duties to the Company.  I agree, at all times during the term of the Relationship and thereafter, to hold in strictest confidence, and not to use, except for the benefit of the Company to the extent necessary to perform my obligations to the Company under the Relationship, and not to disclose to any person, firm, corporation or other entity, without written authorization from the Company in each instance, any Confidential Information that I obtain, access or create during the term of the Relationship, whether or not during working hours, until such Confidential Information becomes publicly and widely known and made generally available through no wrongful act of mine or of others who were under confidentiality obligations as to the item or items involved.  I further agree not to make copies of such Confidential Information except as authorized by the Company.
            (b) Confidential Information.  I understand that ?Confidential Information? means information and physical material not generally known or available outside the Company and information and physical material entrusted to the Company in confidence by third parties.  Confidential Information includes, without limitation:  (i) Company Inventions (as defined below); and (ii) technical data, trade secrets, know-how, research, product or service ideas or plans, software codes and designs, algorithms, developments, inventions, patent applications, laboratory notebooks, processes, formulas, techniques, biological materials, mask works, engineering designs and drawings, hardware configuration information, agreements with third parties, lists of, or information relating to, employees and consultants of the Company (including, but not limited to, the names, contact information, jobs, compensation, and expertise of such employees and consultants), lists of, or information relating to, suppliers and customers (including, but not limited to, customers of the Company on whom I called or with whom I became acquainted during the Relationship), price lists, pricing methodologies, cost data, market share data, marketing plans, licenses, contract information, business plans, financial forecasts, historical financial data, budgets or other business information disclosed to me by the Company either directly or indirectly, whether in writing, electronically, orally, or by observation.
            (c) Third Party Information.  My agreements in this Section?3 are intended to be for the benefit of the Company and any third party that has entrusted information or physical material to the Company in confidence.  I further agree that, during the term of the Relationship and thereafter, I will not improperly use or disclose to the Company any confidential, proprietary or secret information of my former employer(s) or any other person, and I agree not to bring any such information onto the Company?s property or place of business.
            (d) Other Rights.  This Agreement is intended to supplement, and not to supersede, any rights the Company may have in law or equity with respect to the protection of trade secrets or confidential or proprietary information.
      4.    Ownership of Inventions.
            (a) Inventions Retained and Licensed.  I have attached hereto, as Exhibit A, a complete list describing with particularity all Inventions (as defined below) that, as of the Effective Date:  (i) I made, and/or (ii) belong solely to me or belong to me jointly with others or in which I have an interest, and that relate in any way to any of the Company?s actual or proposed businesses, products, services, or research and development, and which are not assigned to the Company hereunder; or, if no such list is attached, I represent that there are no such Inventions at the time of signing this Agreement, and to the extent such Inventions do exist and are not listed on Exhibit?A, I hereby forever waive any and all rights or claims of ownership to such Inventions.  I understand that my listing of any Inventions on Exhibit?A does not constitute an acknowledgement by the Company of the existence or extent of such Inventions, nor of my ownership of such Inventions.  I further understand that I must receive the formal approval of the Company before commencing my Relationship with the Company.
            (b) Use or Incorporation of Inventions.  If in the course of the Relationship, I use or incorporate into a product, service, process or machine any Invention not covered by Section?4(d) of this Agreement in which I have an interest, I will promptly so inform the Company in writing.  Whether or not I give such notice, I hereby irrevocably grant to the Company a nonexclusive, fully paid-up, royalty-free, assumable, perpetual, worldwide license, with right to transfer and to sublicense, to practice and exploit such Invention and to make, have made, copy, modify, make derivative works of, use, sell, import, and otherwise distribute such Invention under all applicable intellectual property laws without restriction of any kind.
            (c) Inventions.  I understand that ?Inventions? means discoveries, developments, concepts, designs, ideas, know how, improvements, inventions, trade secrets and/or original works of authorship, whether or not patentable, copyrightable or otherwise legally protectable.  I understand this includes, but is not limited to, any new product, machine, article of manufacture, biological material, method, procedure, process, technique, use, equipment, device, apparatus, system, compound, formulation, composition of matter, design or configuration of any kind, or any improvement thereon.  I understand that ?Company Inventions? means any and all Inventions that I may solely or jointly author, discover, develop, conceive, or reduce to practice during the period of the Relationship, except as otherwise provided in Section?4(g) below.
            (d) Assignment of Company Inventions.  I agree that I will promptly make full written disclosure to the Company, will hold in trust for the sole right and benefit of the Company, and hereby assign to the Company, or its designee, all my right, title and interest throughout the world in and to any and all Company Inventions and all patent, copyright, trademark, trade secret and other intellectual property rights therein.  I hereby waive and irrevocably quitclaim to the Company or its designee any and all claims, of any nature whatsoever, that I now have or may hereafter have for infringement of any and all Company Inventions.  I further acknowledge that all Company Inventions that are made by me (solely or jointly with others) within the scope of and during the period of the Relationship are ?works made for hire? (to the greatest extent permitted by applicable law) and are compensated by my salary.  Any assignment of Company Inventions includes all rights of attribution, paternity, integrity, modification, disclosure and withdrawal, and any other rights throughout the world that may be known as or referred to as ?moral rights,? ?artist?s rights,? ?droit moral,? or the like (collectively, ?Moral Rights?).  To the extent that Moral Rights cannot be assigned under applicable law, I hereby waive and agree not to enforce any and all Moral Rights, including, without limitation, any limitation on subsequent modification, to the extent permitted under applicable law.
            (e) Maintenance of Records.  I agree to keep and maintain adequate and current written records of all Company Inventions made or conceived by me (solely or jointly with others) during the term of the Relationship.  The records may be in the form of notes, sketches, drawings, flow charts, electronic data or recordings, laboratory notebooks, or any other format.  The records will be available to and remain the sole property of the Company at all times.  I agree not to remove such records from the Company?s place of business except as expressly permitted by Company policy which may, from time to time, be revised at the sole election of the Company for the purpose of furthering the Company?s business.  I agree to deliver all such records (including any copies thereof) to the Company at the time of termination of the Relationship as provided for in Section?5 and Section?6.
            (f) Patent and Copyright Rights.  I agree to assist the Company, or its designee, at its expense, in every proper way to secure the Company?s, or its designee?s, rights in the Company Inventions and any copyrights, patents, trademarks, mask work rights, Moral Rights, or other intellectual property rights relating thereto in any and all countries, including the disclosure to the Company or its designee of all pertinent information and data with respect thereto, the execution of all applications, specifications, oaths, assignments, recordations, and all other instruments which the Company or its designee shall deem necessary in order to apply for, obtain, maintain and transfer such rights, or if not transferable, waive and agree never to assert such rights, and in order to assign and convey to the Company or its designee, and any successors, assigns and nominees the sole and exclusive right, title and interest in and to such Company Inventions, and any copyrights, patents, mask work rights or other intellectual property rights relating thereto.  I further agree that my obligation to execute or cause to be executed, when it is in my power to do so, any such instrument or papers shall continue during and at all times after the end of the Relationship and until the expiration of the last such intellectual property right to expire in any country of the world.  I hereby irrevocably designate and appoint the Company and its duly authorized officers and agents as my agent and attorney-in-fact, to act for and in my behalf and stead to execute and file any such instruments and papers and to do all other lawfully permitted acts to further the application for, prosecution, issuance, maintenance or transfer of letters patent, copyright, mask work and other registrations related to such Company Inventions.  This power of attorney is coupled with an interest and shall not be affected by my subsequent incapacity.
            (g) Exception to Assignments.  Subject to the requirements of applicable state law, if any, I understand that the Company Inventions will not include, and the provisions of this Agreement requiring assignment of inventions to the Company do not apply to, any invention which qualifies fully for exclusion under the provisions of applicable state law, if any.  In order to assist in the determination of which inventions qualify for such exclusion, I will advise the Company promptly in writing, during and after the term of the Relationship, of all Inventions solely or jointly conceived or developed or reduced to practice by me during the period of the Relationship.
      5.    Company Property; Returning Company Documents.  I acknowledge and agree that I have no expectation of privacy with respect to the Company?s telecommunications, networking or information processing systems (including, without limitation, files, e-mail messages, and voice messages) and that my activity and any files or messages on or using any of those systems may be monitored or reviewed at any time without notice.  I further agree that any property situated on the Company?s premises and owned by the Company, including disks and other storage media, filing cabinets or other work areas, is subject to inspection by Company personnel at any time with or without notice.  I agree that, at the time of termination of the Relationship, I will deliver to the Company (and will not keep in my possession, recreate or deliver to anyone else) any and all devices, records, data, notes, reports, proposals, lists, correspondence, specifications, drawings, blueprints, sketches, laboratory notebooks, materials, flow charts, equipment, other documents or property, or reproductions of any of the aforementioned items developed by me pursuant to the Relationship or otherwise belonging to the Company, its successors or assigns.
      6.    Termination Certification.  In the event of the termination of the Relationship, I agree to sign and deliver the ?Termination Certification? attached hereto as Exhibit B; however, my failure to sign and deliver the Termination Certification shall in no way diminish my continuing obligations under this Agreement.
      7.    Notice to Third Parties.  I agree that during the periods of time during which I am restricted in taking certain actions by the terms of this Agreement (the ?Restriction Period?), I shall inform any entity or person with whom I may seek to enter into a business relationship (whether as an owner, employee, independent contractor or otherwise) of my contractual obligations under this Agreement.  I also understand and agree that the Company may, with or without prior notice to me and during or after the term of the Relationship, notify third parties of my agreements and obligations under this Agreement.  I further agree that, upon written request by the Company, I will respond to the Company in writing regarding the status of my employment or proposed employment with any party during the Restriction Period.
      8.    Solicitation of Employees, Consultants and Other Parties.  As described above, I acknowledge and agree that the Company?s Confidential Information includes information relating to the Company?s employees, consultants, customers and others, and that I will not use or disclose such Confidential Information except as authorized by the Company.  I further agree as follows:
            (a) Employees, Consultants. I agree that during the term of the Relationship, and for a period of twelve (12) months immediately following the termination of the Relationship for any reason, whether with or without cause, I shall not, directly or indirectly, solicit, induce, recruit or encourage any of the Company?s employees or consultants to terminate their relationship with the Company, or attempt to solicit, induce, recruit, encourage or take away employees or consultants of the Company, either for myself or for any other person or entity.
            (b) Other Parties.  I agree that during the term of the Relationship, I will not negatively influence any of the Company?s clients, licensors, licensees or customers from purchasing Company products or services or solicit or influence or attempt to influence any client, licensor, licensee, customer or other person either directly or indirectly, to direct any purchase of products and/or services to any person, firm, corporation, institution or other entity in competition with the business of the Company.  In addition, I acknowledge that the Company has valuable Trade Secrets (as defined by applicable law from time to time) to which I will have access during the term of the Relationship.  I understand that the Company intends to vigorously pursue its rights under applicable Trade Secrets law if, during a period of twelve (12) months immediately following the termination of the Relationship for any reason, whether with or without cause, I solicit or influence or attempt to influence any client, licensor, licensee, customer or other person either directly or indirectly, to direct any purchase of products and/or services to any person, firm, corporation, institution or other entity in competition with the business of the Company.  Thereafter, the Company intends to vigorously pursue its rights under applicable Trade Secrets law as the circumstances warrant.
      9.    At-Will Relationship.  I understand and acknowledge that, except as may be otherwise explicitly provided in a separate written agreement between the Company and me, my Relationship with the Company is and shall continue to be at-will, as defined under applicable law, meaning that either I or the Company may terminate the Relationship at any time for any reason or no reason, without further obligation or liability, other than those provisions of this Agreement that explicitly continue in effect after the termination of the Relationship.
      10.   Representations and Covenants.
            (a) Facilitation of Agreement.  I agree to execute promptly, both during and after the end of the Relationship, any proper oath, and to verify any proper document, required to carry out the terms of this Agreement, upon the Company?s written request to do so.
            (b) No Conflicts.  I represent that my performance of all the terms of this Agreement does not and will not breach any agreement I have entered into, or will enter into, with any third party, including without limitation any agreement to keep in confidence proprietary information or materials acquired by me in confidence or in trust prior to or during the Relationship.  I will not disclose to the Company or use any inventions, confidential or non-public proprietary information or material belonging to any previous client, employer or any other party.  I will not induce the Company to use any inventions, confidential or non-public proprietary information, or material belonging to any previous client, employer or any other party.  I acknowledge and agree that I have listed on Exhibit?A all agreements (e.g., non-competition agreements, non-solicitation of customers agreements, non-solicitation of employees agreements, confidentiality agreements, inventions agreements, etc.), if any, with a current or former client, employer, or any other person or entity, that may restrict my ability to accept employment with the Company or my ability to recruit or engage customers or service providers on behalf of the Company, or otherwise relate to or restrict my ability to perform my duties for the Company or any obligation I may have to the Company.  I agree not to enter into any written or oral agreement that conflicts with the provisions of this Agreement.
            (c) Voluntary Execution.  I certify and acknowledge that I have carefully read all of the provisions of this Agreement, that I understand and have voluntarily accepted such provisions, and that I will fully and faithfully comply with such provisions.
      11.   Electronic Delivery.  Nothing herein is intended to imply a right to participate in any of the Company?s equity incentive plans, however, if I do participate in such plan(s), the Company may, in its sole discretion, decide to deliver any documents related to my participation in the Company?s equity incentive plan(s) by electronic means or to request my consent to participate in such plan(s) by electronic means.  I hereby consent to receive such documents by electronic delivery and agree, if applicable, to participate in such plan(s) through an on-line or electronic system established and maintained by the Company or a third party designated by the Company.
      12.   Miscellaneous.
            (a) Governing Law.  The validity, interpretation, construction and performance of this Agreement, and all acts and transactions pursuant hereto and the rights and obligations of the parties hereto shall be governed, construed and interpreted in accordance with the laws of the state of California, without giving effect to the principles of conflict of laws.
            (b) Entire Agreement.  This Agreement sets forth the entire agreement and understanding between the Company and me relating to its subject matter and merges all prior discussions between us.  No amendment to this Agreement will be effective unless in writing signed by both parties to this Agreement.  The Company shall not be deemed hereby to have waived any rights or remedies it may have in law or equity, nor to have given any authorizations or waived any of its rights under this Agreement, unless, and only to the extent, it does so by a specific writing signed by a duly authorized officer of the Company, it being understood that, even if I am an officer of the Company, I will not have authority to give any such authorizations or waivers for the Company under this Agreement without specific approval by the Board of Directors.  Any subsequent change or changes in my duties, obligations, rights or compensation will not affect the validity or scope of this Agreement.
            (c) Successors and Assigns.  This Agreement will be binding upon my heirs, executors, administrators and other legal representatives, and my successors and assigns, and will be for the benefit of the Company, its successors, and its assigns.
            (d) Notices.  Any notice, demand or request required or permitted to be given under this Agreement shall be in writing and shall be deemed sufficient when delivered personally or by overnight courier or sent by email, or 48 hours after being deposited in the U.S. mail as certified or registered mail with postage prepaid, addressed to the party to be notified at such party?s address as set forth on the signature page, as subsequently modified by written notice, or if no address is specified on the signature page, at the most recent address set forth in the Company?s books and records.
            (e) Severability.  If one or more of the provisions in this Agreement are deemed void or unenforceable to any extent in any context, such provisions shall nevertheless be enforced to the fullest extent allowed by law in that and other contexts, and the validity and force of the remainder of this Agreement shall not be affected.  The Company and I have attempted to limit my right to use, maintain and disclose the Company?s Confidential Information, and to limit my right to solicit employees and customers only to the extent necessary to protect the Company from unfair competition.  Should a court of competent jurisdiction determine that the scope of the covenants contained in Section?8 exceeds the maximum restrictiveness such court deems reasonable and enforceable, the parties intend that the court should reform, modify and enforce the provision to such narrower scope as it determines to be reasonable and enforceable under the circumstances existing at that time.
            (f) Remedies.  I acknowledge and agree that violation of this Agreement by me may cause the Company irreparable harm, and therefore I agree that the Company will be entitled to seek extraordinary relief in court, including, but not limited to, temporary restraining orders, preliminary injunctions and permanent injunctions without the necessity of posting a bond or other security (or, where such a bond or security is required, I agree that a $1,000 bond will be adequate), in addition to and without prejudice to any other rights or remedies that the Company may have for a breach of this Agreement.
            (g) Advice of Counsel.  I acknowledge THAT, IN EXECUTING THIS AGREEMENT, I Have HAD THE OPPORTUNITY TO SEEK THE ADVICE OF INDEPENDENT LEGAL COUNSEL, AND I Have read and understood ALL OF THE TERMS AND PROVISIONS OF THIS AGREEMENT.  THIS AGREEMENT SHALL NOT BE CONSTRUED AGAINST ANY PARTY BY REASON OF THE DRAFTING OR PREPARATION HEREOF.
            (h) Counterparts.  This Agreement may be executed in any number of counterparts, each of which when so executed and delivered shall be deemed an original, and all of which together shall constitute one and the same agreement.
[Signature Page Follows]

The parties have executed this Agreement on the respective dates set forth below, to be effective as of the Effective Date first above written.

EXHIBIT?B
TERMINATION CERTIFICATION
      This is to certify that I do not have in my possession, nor have I failed to return, any devices, records, data, notes, reports, proposals, lists, correspondence, specifications, drawings, blueprints, sketches, laboratory notebooks, flow charts, materials, equipment, other documents or property, or copies or reproductions of any aforementioned items belonging to {{CompanyName}}, a Delaware corporation, its subsidiaries, affiliates, successors or assigns (collectively, the ?Company?).
      I further certify that I have complied with all the terms of the Company?s Confidential Information and Invention Assignment Agreement signed by me, including the reporting of any Inventions (as defined therein), conceived or made by me (solely or jointly with others) covered by that agreement, and I acknowledge my continuing obligations under that agreement.
      I further agree that, in compliance with the Confidential Information and Invention Assignment Agreement, I will preserve as confidential all trade secrets, confidential knowledge, data or other proprietary information relating to products, processes, know-how, designs, formulas, developmental or experimental work, computer programs, data bases, other original works of authorship, customer lists, business plans, financial information or other subject matter pertaining to any business of the Company or any of its employees, clients, consultants or licensees.
      I further agree that for twelve (12) months from the date of this Certification, I shall not either directly or indirectly solicit, induce, recruit or encourage any of the Company?s employees or consultants to terminate their relationship with the Company, or attempt to solicit, induce, recruit, encourage or take away employees or consultants of the Company, either for myself or for any other person or entity.
      Further, I agree that I shall not use any Confidential Information of the Company to negatively influence any of the Company?s clients or customers from purchasing Company products or services or to solicit or influence or attempt to influence any client, customer or other person either directly or indirectly, to direct any purchase of products and/or services to any person, firm, corporation, institution or other entity in competition with the business of the Company.
      Further, I acknowledge that the Company has valuable Trade Secrets (as defined by applicable law from time to time) to which I have had access.  I understand that the Company intends to vigorously pursue its rights under applicable Trade Secrets law if, during a period of twelve (12) months from the date of this Certification, I solicit or influence or attempt to influence any client, licensor, licensee, customer or other person either directly or indirectly, to direct any purchase of products and/or services to any person, firm, corporation, institution or other entity in competition with the business of the Company.  Thereafter, the Company intends to vigorously pursue its rights under applicable Trade Secrets law as the circumstances warrant.

the company:
{{CompanyName}}
Title: {{CompanyHRManagerName}}



Employee:  {{EmployeeName}} '
where name='NDA';
